# markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: colingao77
author: "Colin Gao"
email: glct#163.com
name: "Colin's Blog"
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

all_categories: [
["linux", "Linux","/posts/linux.html"],
["read", "Reading","/posts/read.html"], 
["bookmark", "Bookmark","/posts/bookmark.html"],
["fun", "Fun","/posts/fun.html"],
]

all_pages: [
["archive", "Archive","/archives.html"],
["about", "FAQ","/faqs.html"],
["about", "About","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles
future: true

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
