markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: panxw
author: "潘学文"
email: winfirm#163.com
name: "潘学文个人博客"
url: http://www.panxw.com
domain: www.panxw.com
all_categories: [
["linux", "Linux","/posts/linux.html"],
["read", "读书","/posts/read.html"], 
["favorite", "收藏","/posts/favorite.html"],
["fun", "Fun","/posts/fun.html"],
]

all_pages: [
["archive", "存档","/archives.html"],
["about", "FAQ","/faqs.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
